/** 由 site/scripts/extract-articles.mjs 生成 —— 每篇文章的外壳元数据(勿手改,重跑脚本更新) */
export const ARTICLE_SHELL: Record<string, { title: string; accent: string; tint: string }> = {
  "app-shape-for-ai": { title: "SiriAI 设计 · VibeUX", accent: "#5B7FFF", tint: "blue" },
  "astra-three-design-tests": { title: "Astra 三个设计实测，People Use 和 Computer Use 共存 · VibeUX", accent: "#1FA2FF", tint: "blue" },
  "beyond-chat-edit-in-place": { title: "AI 产品设计｜修改在内容上而不是聊天框里 · VibeUX", accent: "#B8550F", tint: "peach" },
  "beyond-chat-prompt-to-controls": { title: "AI 产品设计 ｜ 把高频微调的 Prompt 转变为可复现的参数控件 · VibeUX", accent: "#4FA02A", tint: "mint" },
  "claude-code-suggested-task": { title: "活儿干到一半，Claude Code 反过来给我派任务了 · VibeUX", accent: "#D94F2E", tint: "peach" },
  "claude-code-verification-loops": { title: "验证循环，把手动检查写进 Skill · VibeUX", accent: "#6A823F", tint: "sand" },
  "code-connect-mcp-coverage": { title: "Figma 新推出 Code Connect CLI，给 Agent 读取生产环境的上下文 · VibeUX", accent: "#3392CC", tint: "blue" },
  "codex-voice-delegation": { title: "ChatGPT Voice 用聊天的方式干活，还能随时打断 · VibeUX", accent: "#306DB6", tint: "blue" },
  "figma-agent": { title: "Figma 把 Agent 装进画布，让设计师同时开多个方向 · VibeUX", accent: "#3B82F6", tint: "blue" },
  "figma-config-2026": { title: "设计师被 AI 替代之前，Figma 用一整套新功能抬高设计师上限 · VibeUX", accent: "#D4A017", tint: "sand" },
  "figma-make-designer-pr": { title: "AI native 设计师的交付物，不只设计稿，还有 GitHub PR · VibeUX", accent: "#2F3336", tint: "gray" },
  "figma-make-gpt-5-6": { title: "设计师的新习惯，给 AI 模型分工 · VibeUX", accent: "#5F82F5", tint: "blue" },
  "figma-shader-motion": { title: "在设计系统里，Figma Shader 和 Motion ，正从效果变成可复用元素 · VibeUX", accent: "#7C4DFF", tint: "violet" },
  "figma-skills": { title: "设计师的新资产，是 Skills · VibeUX", accent: "#D4A017", tint: "sand" },
  "genie": { title: "Genie 给 AI 装了一具身体：光、物理和触感 · VibeUX", accent: "#06B6D4", tint: "mint" },
  "genui-no-style-to-write": { title: "跳过 Figma 直接用 GenUI 做设计，踩了一路坑，也跑通了上线 · VibeUX", accent: "#1C1B1B", tint: "gray" },
  "long-chat-navigation-design": { title: "AI 产品设计｜长对话导航机制 · VibeUX", accent: "#5B6FE8", tint: "blue" },
  "remove-ai-taste-in-design": { title: "看不出 AI 味的 AI 设计方式 · VibeUX", accent: "#5A6CD8", tint: "blue" },
  "review-ai-output": { title: "设计师的新工作，审查 AI 产物 · VibeUX", accent: "#0E9E6E", tint: "mint" },
  "selection-as-context": { title: "AI 产品设计｜选中即上下文 · VibeUX", accent: "#4B5FE8", tint: "blue" },
  "sparkle": { title: "AI 符号被秒懂，是调用了成熟的用户心智模型 · VibeUX", accent: "#6F8FC4", tint: "blue" },
  "voices": { title: "Voices · VibeUX", accent: "#D6558E", tint: "rose" },
};
